### ISSUE TITLE
Can you provide the License for this repo?

### ISSUE THREAD

**Issue by Hab2Verer** [Ebimsv/Facial_Age_estimation_PyTorch#1]
Great work!
I am planning to use your code in a project.
What is the License for this repo?
Thanks in advance.

**Comment by Ebimsv** [comment]
I'm glad to hear that you find this repository useful! Thank you for your interest in using the code for your project.

Regarding the license, I have not yet selected one for this repository. Could you please let me know if you have any preferences or specific requirements for the license? This will help me decide on the most appropriate license to apply.

Looking forward to your response.

Best regards,

**Comment by Hab2Verer** [comment]
Usually, the [MIT License](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt) is used, it is permissive and allows for collaboration.
You can easily [add it](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to your project.

Happy to help.

**Comment by Ebimsv** [comment]
I have added the MIT License to my project as recommended.
